### ISSUE TITLE
The 'close tab after some time' box says 'close FB' on any custom site

### ISSUE THREAD

**Issue by brahmcapoor** [habitlab/habitlab-chrome#101]
![screen shot 2016-11-05 at 9 40 19 pm](https://cloud.githubusercontent.com/assets/18450524/20035412/9c1b68fe-a3a0-11e6-8fa4-19daf2342076.png)

**Comment by brahmcapoor** [comment]
Also, the countdown is clipping out of the box

**Comment by brahmcapoor** [comment]
Potential quick fix: change "Close FB" to "Close Tab" in the time-until-tab-autoclose-view and timespent-view components

**Comment by gkovacs** [comment]
the issue with the text overflowing seems to be due to slashdot's CSS leaking over (default fontface and size), I'm looking into a non-hackish solution to this as slashdot is not the only site on which this issue is going to occur
