### ISSUE TITLE
Extension has no easy way to open up the options and dashboard if an intervention is active

### ISSUE THREAD

**Issue by mbernst** [habitlab/habitlab-chrome#2]
If an intervention is active:
<img width="520" alt="screen shot 2016-07-02 at 8 40 45 am" src="https://cloud.githubusercontent.com/assets/249285/16541178/b53bedfa-4030-11e6-9bcc-06f3b47f8976.png">

If there's not one active, there's a link:
<img width="199" alt="screen shot 2016-07-02 at 8 41 14 am" src="https://cloud.githubusercontent.com/assets/249285/16541179/c03676bc-4030-11e6-897f-2d4ff1b424a0.png">

**Comment by mbernst** [comment]
Sorry, it appears as if it's not about whether the intervention is "active", but whether one matches the a URL pattern, regardless of whether it's activated?

**Comment by smsukardi** [comment]
I believe that it's added onto the list if it's active in the sense that the checkbox is checked on the settings page; not necessarily that it's being currently deployed at the very moment. The way the list is decided is done by getting the current website url and seeing which interventions are active that match that certain url.
Options button has been added.
