### ISSUE TITLE
snooze interventions

### ISSUE THREAD

**Issue by gkovacs** [habitlab/habitlab-chrome#26]
it appears the usage scenario for our "smartly managed" interventions is "I want to keep this enabled, but not right now". to address this, under the habitlab-logo component, we should have a snooze button that disables it for some duration of time (ie, 1 hour). so under habitlab-logo, we have options

* Disable this intevention permanently
* Snooze this intervention for 1 hour

**Comment by mathieurolfo** [comment]
we can include/leave the duration of the snooze in the menu bar

**Comment by gkovacs** [comment]
actually we might consider having the duration be "snooze this intervention for the rest of today", as it would help reinforce a mental model of "new interventions appear each day" (ie, everything changes only daily and not any sooner). probably want to ask around what the appropriate length of snoozing would be.
