### ISSUE TITLE
components/popup-view should probably allow people to snooze or turn off the interventions from there

### ISSUE THREAD

**Issue by gkovacs** [habitlab/habitlab-chrome#34]
see components/habitlab-logo for example

also you should use https://www.polymer-project.org/1.0/docs/devguide/templates#dom-repeat for the iteratively-creating-com-elements instead of jquery, code will look cleaner. see components/options-interventions or components/options-goals for example

also the button to go to the configuration page from there should be bigger, probably use a paper-button. maybe split into 2 buttons if not too cluttered (one goes to the dashboard, the other goes to the configuration page)

**Comment by smsukardi** [comment]
Fixed in commit ec6a7fc
