### ISSUE TITLE
remind users that they have/haven't achieved their goal the next day they open their browser

### ISSUE THREAD

**Issue by gkovacs** [habitlab/habitlab-chrome#96]
components/goal-progress-view.ls and components/goal-progress-view.html is the visualization that is on the options page

in order to get the information that is populated there,

get_progress_on_goal_this_week (in libs_backend/goal_progress)

get_goal_target (in libs_backend/goal_utils)

get_enabled_goals (in libs_backend/goal_utils)

get_goals (in libs_backend/goal_utils)

lewin: working on a notification that will show up (implemented in the background script)

brahm: working on the visualization that it will link to once you click on that notification

**Comment by brahmcapoor** [comment]
I think what I'm going to do is just add a new section to the 'View Progress and Results' pane of the options page. `components/goal-progress-view.ls` and `components/goal-progress-view.html` seem to be one particular visualization on that page - where can I find the files that control the page (which has multiple visualizations) itself?

**Comment by gkovacs** [comment]
@brahmcapoor you make it show up under the View Progress and Results tab by adding the new component to the dashboard-view component ( https://github.com/habitlab/habitlab-chrome/blob/master/src/components/dashboard-view.html ). [In general, you can find out how components are nested by opening the web inspector and going up the DOM hierarchy; if you do so on the View Progress and Results tab then you will see that those graphs are all under dashboard-view]

**Comment by brahmcapoor** [comment]
@gkovacs got it, thanks

**Comment by gkovacs** [comment]
(lewin+brahm's feature have addressed this)
