### ISSUE TITLE
some interventions need ability to be temporarily disabled

### ISSUE THREAD

**Issue by gkovacs** [habitlab/habitlab-chrome#98]
youtube/remove_comment_section
reddit/remove-comment-links (this intervention should probably also replace the popup upon with something less intrusive - ie, just insert some thin banner at the top that tells them the comments section has been hidden)

could follow the model of the facebook/remove_news_feed intervention

**Comment by brahmcapoor** [comment]
@gkovacs Are there any banner-like polymer components?

**Comment by gkovacs** [comment]
@brahmcapoor or if you mean banner that is at the top of the screen regardless of where you scroll, use a div with the css "position: fixed" property

**Comment by brahmcapoor** [comment]
@gkovacs okay, cool - I was just wondering if we were using a polymer banner component to make sure the style was consistent. I added an option using sweetalert to temporarily disable the intervention, I'll work on switching it to a banner.

**Comment by lewincary** [comment]
Youtube comment intervention can now be disabled!

**Comment by gkovacs** [comment]
@lewincary great! you may also want to have a habitlab-logo over where the comments section would normally be (and a paper-button that can be clicked to show the comments, like in the facebook/remove_comments intervention), just so users are not left wondering why no comments are being shown

**Comment by lewincary** [comment]
Yep, I already put a paper button in - I haven't put the logo with it, will do.

**Comment by gkovacs** [comment]
the youtube remove comments intervention is fixed for disabling. opened new issue https://github.com/habitlab/habitlab-chrome/issues/114 specific to the reddit one
